//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OppilasSovellus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oppilastiedot
    {

        
        public int id { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Postinumero { get; set; }
        public string Paikkakunta { get; set; }
        public string Osoite { get; set; }
        public string Syntymapaiva { get; set; }
        public string OnOppilas { get; set; }
    }
}
